//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CriterionsDependency
    {
        public short CriterionsDependencyCode { get; set; }
        public Nullable<short> CriterionofAreaCode1 { get; set; }
        public Nullable<short> CriterionofAreaCode2 { get; set; }
    
        public virtual CriterionsofAreas CriterionsofAreas { get; set; }
        public virtual CriterionsofAreas CriterionsofAreas1 { get; set; }
    }
}
