//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class CriterionsofRequests
    {
        public short CriterionsofRequestsCode { get; set; }
        public Nullable<short> RequestCode { get; set; }
        public Nullable<short> CriterionofAreaCode { get; set; }
        public string ValueofCriterion { get; set; }
        public Nullable<short> LevelofImportance { get; set; }
    
        public virtual CriterionsofAreas CriterionsofAreas { get; set; }
        public virtual Requests Requests { get; set; }
    }
}
