//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class JOBBAEntities : DbContext
    {
        public JOBBAEntities()
            : base("name=JOBBAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Areas> Areas { get; set; }
        public virtual DbSet<AreasTitles> AreasTitles { get; set; }
        public virtual DbSet<Criterions> Criterions { get; set; }
        public virtual DbSet<CriterionsDependency> CriterionsDependency { get; set; }
        public virtual DbSet<CriterionsofAreas> CriterionsofAreas { get; set; }
        public virtual DbSet<CriterionsofRequests> CriterionsofRequests { get; set; }
        public virtual DbSet<CriterionsTitles> CriterionsTitles { get; set; }
        public virtual DbSet<JobsAppliedFor> JobsAppliedFor { get; set; }
        public virtual DbSet<OfferDetails> OfferDetails { get; set; }
        public virtual DbSet<People> People { get; set; }
        public virtual DbSet<PeopleValidation> PeopleValidation { get; set; }
        public virtual DbSet<Requests> Requests { get; set; }
        public virtual DbSet<Validations> Validations { get; set; }
    }
}
