//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class OfferDetails
    {
        public short OfferDetailsCode { get; set; }
        public Nullable<short> RequestCode { get; set; }
        public Nullable<short> AreaCode { get; set; }
        public string OfferName { get; set; }
        public string OfferDescription { get; set; }
        public string MoreDetails { get; set; }
    
        public virtual Areas Areas { get; set; }
        public virtual Requests Requests { get; set; }
    }
}
