//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class People
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public People()
        {
            this.JobsAppliedFor = new HashSet<JobsAppliedFor>();
            this.PeopleValidation = new HashSet<PeopleValidation>();
            this.Requests = new HashSet<Requests>();
        }
    
        public short PeopleCode { get; set; }
        public string PeoplePassword { get; set; }
        public string TempPassword { get; set; }
        public string FirstName { get; set; }
        public string LastNameorBisnessname { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<bool> Administrator { get; set; }
        public string Logo { get; set; }
        public string SiteLink { get; set; }
        public string About { get; set; }
        public string CV { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobsAppliedFor> JobsAppliedFor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PeopleValidation> PeopleValidation { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Requests> Requests { get; set; }
    }
}
