//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Requests()
        {
            this.CriterionsofRequests = new HashSet<CriterionsofRequests>();
            this.JobsAppliedFor = new HashSet<JobsAppliedFor>();
            this.OfferDetails = new HashSet<OfferDetails>();
        }
    
        public short RequestCode { get; set; }
        public Nullable<short> PeopleCode { get; set; }
        public Nullable<short> AreaCode { get; set; }
        public string AreaTitles { get; set; }
        public string Place { get; set; }
        public Nullable<double> EmployTravelTime { get; set; }
        public Nullable<bool> Employee { get; set; }
        public Nullable<bool> SendingJobOffersOnceaDay { get; set; }
        public Nullable<bool> SendingJobOffersWheneverThereIsaSuitableOffer { get; set; }
    
        public virtual Areas Areas { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CriterionsofRequests> CriterionsofRequests { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobsAppliedFor> JobsAppliedFor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OfferDetails> OfferDetails { get; set; }
        public virtual People People { get; set; }
    }
}
